server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-password: secret
    key-store-type: JKS
    key-alias: server
    key-store-password: secret

spring:
  thymeleaf:
    reactive:
      max-chunk-size: 8192

  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

  datasource:
    url: jdbc:hsqldb:file:./langbookweb_db;hsqldb.lob_compressed=true
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog.yml