//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 05:43:40 PM MSK 
//


package ru.home.langbookweb.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}word"/>
 *         &lt;element ref="{}meanings"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "word",
    "meanings"
})
@XmlRootElement(name = "card")
public class Card {

    @XmlElement(required = true)
    protected Word word;
    @XmlElement(required = true)
    protected Meanings meanings;

    /**
     * Gets the value of the word property.
     * 
     * @return
     *     possible object is
     *     {@link Word }
     *     
     */
    public Word getWord() {
        return word;
    }

    /**
     * Sets the value of the word property.
     * 
     * @param value
     *     allowed object is
     *     {@link Word }
     *     
     */
    public void setWord(Word value) {
        this.word = value;
    }

    /**
     * Gets the value of the meanings property.
     * 
     * @return
     *     possible object is
     *     {@link Meanings }
     *     
     */
    public Meanings getMeanings() {
        return meanings;
    }

    /**
     * Sets the value of the meanings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meanings }
     *     
     */
    public void setMeanings(Meanings value) {
        this.meanings = value;
    }

}
