//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 05:43:40 PM MSK 
//


package ru.home.langbookweb.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}statistics"/>
 *         &lt;element ref="{}card" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="formatVersion" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="nextWordId" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sourceLanguageId" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="destinationLanguageId" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statistics",
    "card"
})
@XmlRootElement(name = "dictionary")
public class Dictionary {

    @XmlElement(required = true)
    protected Statistics statistics;
    protected List<Card> card;
    @XmlAttribute(name = "formatVersion")
    protected Byte formatVersion;
    @XmlAttribute(name = "nextWordId")
    protected Byte nextWordId;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "sourceLanguageId")
    protected Short sourceLanguageId;
    @XmlAttribute(name = "destinationLanguageId")
    protected Short destinationLanguageId;

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Statistics }
     *     
     */
    public Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistics }
     *     
     */
    public void setStatistics(Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the card property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Card }
     * 
     * 
     */
    public List<Card> getCard() {
        if (card == null) {
            card = new ArrayList<Card>();
        }
        return this.card;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFormatVersion() {
        return formatVersion;
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFormatVersion(Byte value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the nextWordId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNextWordId() {
        return nextWordId;
    }

    /**
     * Sets the value of the nextWordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNextWordId(Byte value) {
        this.nextWordId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the sourceLanguageId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSourceLanguageId() {
        return sourceLanguageId;
    }

    /**
     * Sets the value of the sourceLanguageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSourceLanguageId(Short value) {
        this.sourceLanguageId = value;
    }

    /**
     * Gets the value of the destinationLanguageId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDestinationLanguageId() {
        return destinationLanguageId;
    }

    /**
     * Sets the value of the destinationLanguageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDestinationLanguageId(Short value) {
        this.destinationLanguageId = value;
    }

}
