//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 05:43:40 PM MSK 
//


package ru.home.langbookweb.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}statistics"/>
 *         &lt;element ref="{}translations"/>
 *         &lt;element ref="{}examples"/>
 *       &lt;/sequence>
 *       &lt;attribute name="meaningId" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="partOfSpeech" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="transcription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sound" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statistics",
    "translations",
    "examples"
})
@XmlRootElement(name = "meaning")
public class Meaning {

    @XmlElement(required = true)
    protected Statistics statistics;
    @XmlElement(required = true)
    protected Translations translations;
    @XmlElement(required = true)
    protected Examples examples;
    @XmlAttribute(name = "meaningId")
    protected Byte meaningId;
    @XmlAttribute(name = "partOfSpeech")
    protected Byte partOfSpeech;
    @XmlAttribute(name = "transcription")
    protected String transcription;
    @XmlAttribute(name = "sound")
    protected String sound;

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Statistics }
     *     
     */
    public Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistics }
     *     
     */
    public void setStatistics(Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the translations property.
     * 
     * @return
     *     possible object is
     *     {@link Translations }
     *     
     */
    public Translations getTranslations() {
        return translations;
    }

    /**
     * Sets the value of the translations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Translations }
     *     
     */
    public void setTranslations(Translations value) {
        this.translations = value;
    }

    /**
     * Gets the value of the examples property.
     * 
     * @return
     *     possible object is
     *     {@link Examples }
     *     
     */
    public Examples getExamples() {
        return examples;
    }

    /**
     * Sets the value of the examples property.
     * 
     * @param value
     *     allowed object is
     *     {@link Examples }
     *     
     */
    public void setExamples(Examples value) {
        this.examples = value;
    }

    /**
     * Gets the value of the meaningId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMeaningId() {
        return meaningId;
    }

    /**
     * Sets the value of the meaningId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMeaningId(Byte value) {
        this.meaningId = value;
    }

    /**
     * Gets the value of the partOfSpeech property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPartOfSpeech() {
        return partOfSpeech;
    }

    /**
     * Sets the value of the partOfSpeech property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPartOfSpeech(Byte value) {
        this.partOfSpeech = value;
    }

    /**
     * Gets the value of the transcription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranscription() {
        return transcription;
    }

    /**
     * Sets the value of the transcription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranscription(String value) {
        this.transcription = value;
    }

    /**
     * Gets the value of the sound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSound() {
        return sound;
    }

    /**
     * Sets the value of the sound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSound(String value) {
        this.sound = value;
    }

}
