<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" preserveAspectRatio="none">
    <g>
        <rect width="${width}" height="${height}" fill="#777"></rect>
        <g>
            <text x="${x1}" y="${y1}" text-anchor="middle" style="fill:#555;font-weight:normal;font-family:Helvetica,monospace;font-size:40pt">${word}</text>
            <text x="${x2}" y="${y2}" text-anchor="middle" style="fill:#555;font-weight:normal;font-family:Helvetica,monospace;font-size:30pt">${type}</text>
        </g>
    </g>
</svg>